### ISSUE TITLE
how to get the blas plugin?

### ISSUE THREAD

**Issue by xvim** [cloudkernels/vaccelrt#74]
I want to try to do Matrix-to-matrix multiplication,but can not find the related plugin to run sgemm, use noop only get the fake output

$ sgemm
[noop] Calling sgemm for session 1
[noop] Dumping arguments for sgemm:
[noop] m: 512 n: 512 k: 512
[noop] alpha: 32412.000000
[noop] A: 0x7ffc63ee1dc0 lda: 512
[noop] B: 0x7ffc63fe1dc0 ldb: 512
[noop] beta: 2123.000000
[noop] C: 0x7ffc640e1dc0 ldc: 512

**Comment by ananos** [comment]
Hi @xvim! 

thanks for your interest on vAccel!  

vaccelrt is the core library that exposes the API and provides the functionality to include plugins. In the core library repo you can find the noop plugin, a debug plugin that showcases the functionality of each API call.

An example "hardware" (GPU) plugin for SGEMM is here: https://github.com/nubificus/serrano-plugin-gpu -- same for a dummy CPU implementation: https://github.com/nubificus/serrano-plugin-cpu.

You can have a look at https://docs.vaccel.org for more information, and specifically: https://docs.vaccel.org/plugin/ to understand how you can write your own plugin. Also, there are some tutorial-like resources you could follow: https://github.com/nubificus/vaccel-tutorials. If you're interested in running on a VM (or remotely) consider getting binaries from https://docs.vaccel.org/binaries.

Have a look and let us know if you manage to get it to work!

**Comment by ananos** [comment]
stale, closing for now. @xvim please give us a shout if you still have issues.
